# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

dc = Publisher.create(name: "DC")
marvel = Publisher.create(name: "Marvel")
vertigo = Publisher.create(name: "Vertigo")
image = Publisher.create(name: "Image")
topshelf = Publisher.create(name: "Top Shelf")
fantagraphics = Publisher.create(name: "Fantagraphics")
dq = Publisher.create(name: "Drawn & Quarterly")
humanoids = Publisher.create(name: "Humanoids")
titan = Publisher.create(name: "Titan Books")
graphitti = Publisher.create(name: "Graphitti Designs")
longmeadow = Publisher.create(name: "Longmeadow Press")

gian = User.create(username: "gian", email: "gianfakeemail@gmail.com", password: "1234")
salem = User.create(username: "salem", email: "salemfakeemail@gmail.com", password: "1234")

Book.create(publisher_id: dc.id, user_id: gian.id, name: "Superman: Red Son", writer: "Mark Millar", edition: "Hardcover", image_url: "https://m.media-amazon.com/images/I/51Phw2M63RL._AC_SY1000_.jpg")
Book.create(publisher_id: graphitti.id, user_id: gian.id, name: "Watchmen", writer: "Alan Moore", edition: "Leatherbound", image_url: "https://s3.amazonaws.com/comicgeeks/comics/covers/large-5561078.jpg?1525311561")
Book.create(publisher_id: graphitti.id, user_id: gian.id, name: "The Crow", writer: "James O'Barr", edition: "Leatherbound", image_url: "https://iwt.sfo2.cdn.digitaloceanspaces.com/cbr-covers/f3739a1ca0e9816f00d4efae1cf7b2b5_xl.jpg")
Book.create(publisher_id: longmeadow.id, user_id: gian.id, name: "The Complete Frank Miller Batman", writer: "Frank Miller", edition: "Leatherbound", image_url: "https://www.budsartbooks.com/wp-content/uploads/2022/07/RB3731-complete-frank-miller-batman.jpg")
Book.create(publisher_id: longmeadow.id, user_id: gian.id, name: "Stacked Deck: The Greatest Joker Stories Ever Told", writer: "Various", edition: "Leatherbound", image_url: "https://i.ebayimg.com/images/g/hc4AAOSwWbpjyqOc/s-l1600.jpg")
Book.create(publisher_id: marvel.id, user_id: gian.id, name: "X-Men: Day of Future Past", writer: "Chris Claremont", edition: "Hardcover", image_url: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1393227496i/18359970.jpg")
Book.create(publisher_id: marvel.id, user_id: gian.id, name: "X-Men: Dark Phoenix Saga", writer: "Chris Claremont", edition: "Hardcover", image_url: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/61FgBxfWLoL._AC_UF1000,1000_QL80_.jpg")
Book.create(publisher_id: marvel.id, user_id: gian.id, name: "X-Men: God Loves, Man Kills", writer: "Chris Claremont", edition: "Hardcover", image_url: "https://cdn.shopify.com/s/files/1/0012/3866/3275/products/x-men-comic-god-loves-man-kills-chris-claremont.jpg?v=1585888609")
Book.create(publisher_id: marvel.id, user_id: gian.id, name: "X-Men: Mutant Genesis", writer: "Chris Claremont", edition: "Hardcover", image_url: "https://m.media-amazon.com/images/I/51vr1X7h+ML.jpg")
Book.create(publisher_id: marvel.id, user_id: gian.id, name: "Wolverine", writer: "Chris Claremont and Frank Miller", edition: "Hardcover", image_url: "https://m.media-amazon.com/images/I/81Z-gMSUlvL._AC_UF1000,1000_QL80_.jpg")
Book.create(publisher_id: marvel.id, user_id: gian.id, name: "Wolverine: Weapon X", writer: "Barry Windsor-Smith", edition: "Hardcover", image_url: "https://cdn.marvel.com/u/prod/marvel/i/mg/2/30/58b5cfccd2eb2/clean.jpg")
Book.create(publisher_id: marvel.id, user_id: gian.id, name: "Astonishing X-Men Vol. 1", writer: "Joss Whedon", edition: "Hardcover", image_url: "https://d1466nnw0ex81e.cloudfront.net/n_iv/600/599703.jpg")
Book.create(publisher_id: marvel.id, user_id: gian.id, name: "Astonishing X-Men Vol. 2", writer: "Joss Whedon", edition: "Hardcover", image_url: "https://d1466nnw0ex81e.cloudfront.net/n_iv/600/1126465.jpg")
Book.create(publisher_id: vertigo.id, user_id: gian.id, name: "Death: Deluxe Edition", writer: "Neil Gaiman", edition: "Hardcover", image_url: "https://m.media-amazon.com/images/P/B09TV116RT.01._SCLZZZZZZZ_SX500_.jpg")
Book.create(publisher_id: humanoids.id, user_id: gian.id, name: "Madwoman of the Sacred Heart", writer: "Alejandro Jodorowsky and Moebius", edition: "Hardcover", image_url: "https://cdn2.humanoids.com/assets/CatalogueArticle/402/Madwoman-2_R400.jpg")
Book.create(publisher_id: humanoids.id, user_id: gian.id, name: "I am Legion", writer: "Fabien Nury", edition: "Hardcover", image_url: "http://www.humanoids.com/assets/CatalogueArticle/354/I-m-legion-3_zoomed.jpg")
Book.create(publisher_id: fantagraphics.id, user_id: gian.id, name: "Maggie the Mechanic: A Love and Rockets Book", writer: "Jaime Hernandez", edition: "Softcover", image_url: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/51lwWD2ohhL.jpg")
Book.create(publisher_id: fantagraphics.id, user_id: gian.id, name: "The Girl from H.O.P.P.E.R.S.: A Love and Rockets Book", writer: "Jaime Hernandez", edition: "Softcover", image_url: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/716b9kDVwtL.jpg")
Book.create(publisher_id: fantagraphics.id, user_id: gian.id, name: "Perla La Loca: A Love and Rockets Book", writer: "Jaime Hernandez", edition: "Softcover", image_url: "https://blackwells.co.uk/jacket/l/9781560978831.jpg")
Book.create(publisher_id: fantagraphics.id, user_id: gian.id, name: "Penny Century: A Love and Rockets Book", writer: "Jaime Hernandez", edition: "Softcover", image_url: "https://cdn.shopify.com/s/files/1/0358/5520/4489/products/STK408652_580x.jpg?v=1654125224")
Book.create(publisher_id: fantagraphics.id, user_id: gian.id, name: "Esperanza: A Love and Rockets Book", writer: "Jaime Hernandez", edition: "Softcover", image_url: "https://m.media-amazon.com/images/I/51E5FVEW3pL.jpg")
Book.create(publisher_id: fantagraphics.id, user_id: gian.id, name: "Angels and Magpies: A Love and Rockets Book", writer: "Jaime Hernandez", edition: "Softcover", image_url: "https://www.forewordreviews.com/books/covers/angels-and-magpies.jpg")
Book.create(publisher_id: dc.id, user_id: gian.id, name: "Sandman: Deluxe Edition 1", writer: "Neil Gaiman", edition: "Hardcover", image_url: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/A10o41YYTDL._AC_UF1000,1000_QL80_.jpg")
Book.create(publisher_id: dc.id, user_id: gian.id, name: "Sandman: Deluxe Edition 2", writer: "Neil Gaiman", edition: "Hardcover", image_url: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/A1D2aG9sQnL._AC_UF1000,1000_QL80_.jpg")
Book.create(publisher_id: dc.id, user_id: gian.id, name: "Sandman: Deluxe Edition 3", writer: "Neil Gaiman", edition: "Hardcover", image_url: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/91B6xsaAX1L._AC_UF1000,1000_QL80_.jpg")
Book.create(publisher_id: dc.id, user_id: gian.id, name: "Sandman: Deluxe Edition 4", writer: "Neil Gaiman", edition: "Hardcover", image_url: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/A1OsHR158DL._AC_UF1000,1000_QL80_.jpg")
Book.create(publisher_id: marvel.id, user_id: gian.id, name: "X-Men: House of X", writer: "Jonathan Hickman", edition: "Hardcover", image_url: "https://d1466nnw0ex81e.cloudfront.net/n_iv/600/5305368.jpg")
Book.create(publisher_id: dq.id, user_id: gian.id, name: "Shortcomings", writer: "Adrian Tomine", edition: "Hardcover", image_url: "https://images.booksense.com/images/166/299/9781897299166.jpg")
Book.create(publisher_id: dq.id, user_id: gian.id, name: "Summer Blonde", writer: "Adrian Tomine", edition: "Hardcover", image_url: "https://i.ebayimg.com/images/g/t7QAAOSwDLdhVTgx/s-l500.jpg")
Book.create(publisher_id: dq.id, user_id: gian.id, name: "Sleepwalk and Other Stories", writer: "Adrian Tomine", edition: "Hardcover", image_url: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/91fMSeBlI-L.jpg")
Book.create(publisher_id: dq.id, user_id: gian.id, name: "Scenes From an Impending Marriage", writer: "Adrian Tomine", edition: "Hardcover", image_url: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/41dEugLBFxL._SX422_BO1,204,203,200_.jpg")
Book.create(publisher_id: dq.id, user_id: gian.id, name: "Killing and Dying", writer: "Adrian Tomine", edition: "Hardcover", image_url: "https://didyoueverstoptothink.files.wordpress.com/2022/01/killing_and_dying_cover.jpg")
Book.create(publisher_id: dq.id, user_id: gian.id, name: "The Loneliness of the Long-Distance Cartoonist", writer: "Adrian Tomine", edition: "Hardcover", image_url: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/715dUArjIpL.jpg")
Book.create(publisher_id: dq.id, user_id: gian.id, name: "32 Stories", writer: "Adrian Tomine", edition: "Box Set", image_url: "https://drawnandquarterly.com/wp-content/uploads/2013/06/32stories_NEW_edition_web.jpg")
Book.create(publisher_id: dq.id, user_id: gian.id, name: "New York Drawings", writer: "Adrian Tomine", edition: "Hardcover", image_url: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/81SdbF-YdWL.jpg")
Book.create(publisher_id: topshelf.id, user_id: gian.id, name: "Blankets", writer: "Craig Thompson", edition: "Hardcover", image_url: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/81ClZo93byL._AC_UF1000,1000_QL80_.jpg")
Book.create(publisher_id: dq.id, user_id: gian.id, name: "Berlin", writer: "Jason Lutes", edition: "Hardcover", image_url: "https://drawnandquarterly.com/wp-content/uploads/biblioshare_attachments/9781770463264.png")
Book.create(publisher_id: image.id, user_id: gian.id, name: "The Complete Phonogram", writer: "Kieron Gillen and Jamie Mckelvie", edition: "Hardcover", image_url: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/414YfyO2vzL._SX323_BO1,204,203,200_.jpg")

Book.create(publisher_id: dc.id, user_id: salem.id, name: "V for Vendetta", writer: "Alan Moore", edition: "Hardcover", image_url: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/810o0N-Z2OL._AC_UF1000,1000_QL80_.jpg")
Book.create(publisher_id: topshelf.id, user_id: salem.id, name: "From Hell: Master Edition", writer: "Alan Moore", edition: "Hardcover", image_url: "https://m.media-amazon.com/images/I/512ADylHObL.jpg")
Book.create(publisher_id: marvel.id, user_id: salem.id, name: "Darth Vader Vol.1", writer: "Kieron Gillen", edition: "Hardcover", image_url: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/91xYYNaab+L.jpg")
Book.create(publisher_id: marvel.id, user_id: salem.id, name: "Darth Vader Vol.2", writer: "Kieron Gillen", edition: "Hardcover", image_url: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/512LWEHnUSL.jpg")
Book.create(publisher_id: titan.id, user_id: salem.id, name: "Spawn: Creation", writer: "Todd McFarlane", edition: "Hardcover", image_url: "https://m.media-amazon.com/images/I/51ZQXM4HDFL._AC_UF1000,1000_QL80_.jpg")